version: '3'

volumes:
  etcd-data:
    name: 'etcd-data'
    labels:
      - "co.anitrend.id=etcd-data"
    driver: local

services:
  etcd:
    container_name: "apisix-etcd"
    image: bitnami/etcd:3.5.18
    networks:
      - default
    env_file: 
      - .env
    volumes:
      - etcd-data:/bitnami/etcd
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"


networks:
  default:
    name: traefik
    external: true