version: '3'
services:
  etcd:
    container_name: "apisix-etcd"
    image: bitnami/etcd:3.5.13
    networks:
      - default
    env_file: 
      - .env
    volumes:
      - ./data:/bitnami/etcd
    ports:
      - "${PORT}:${PORT}/tcp"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"


networks:
  default:
    name: traefik
    external: true