version: '3'

services:
  growthbook:
    image: "growthbook/growthbook:2.9.0"
    container_name: growthbook
    volumes:
      - ./data/uploads:/usr/local/src/app/packages/back-end/uploads
    env_file: .env
    ports:
      - ${DASHBOARD_PORT}:3000
      - ${API_PORT}:3100
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.growth-dashboard.rule=Host(`${DASHBOARD_HOST}`)'
      - 'traefik.http.services.growth-dashboard.loadbalancer.server.port=${DASHBOARD_PORT}'
      - 'traefik.http.routers.growth-dashboard.entrypoints=web,websecure'
      - 'traefik.http.routers.growth-dashboard.service=growth-dashboard'
      - 'traefik.http.routers.growth-dashboard.tls=true'
      - 'traefik.http.routers.growth-dashboard.tls.certresolver=${CERT_RESOLVER}'
      - 'traefik.http.routers.growth-api.rule=Host(`${API_HOST}`)'
      - 'traefik.http.services.growth-api.loadbalancer.server.port=${API_PORT}'
      - 'traefik.http.routers.growth-api.entrypoints=web,websecure'
      - 'traefik.http.routers.growth-api.service=growth-api'
      - 'traefik.http.routers.growth-api.tls=true'
      - 'traefik.http.routers.growth-api.tls.certresolver=${CERT_RESOLVER}'
    networks:
      - default
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: traefik
    external: true
