volumes:
  uploads:
    name: 'growthbook_dashboard-uploads'
    labels:
      - "co.anitrend.id=dashboard-uploads"
    driver: local

services:
  growthbook:
    container_name: "growthbook"
    image: "growthbook/growthbook:3.4.0"
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
    env_file: ./dashboard/.env
    labels:
      - 'traefik.enable=${TRAEFIK_ENABLE}'
      - 'traefik.http.routers.growth-dashboard.rule=Host(`${DASHBOARD_HOST}`)'
      - 'traefik.http.services.growth-dashboard.loadbalancer.server.port=${DASHBOARD_PORT}'
      - 'traefik.http.routers.growth-dashboard.entrypoints=web,websecure'
      - 'traefik.http.routers.growth-dashboard.service=growth-dashboard'
      - 'traefik.http.routers.growth-dashboard.tls=true'
      - 'traefik.http.routers.growth-dashboard.tls.certresolver=${CERT_RESOLVER}'
      - 'traefik.http.routers.growth-api.rule=Host(`${DASHBOARD_API_HOST}`)'
      - 'traefik.http.services.growth-api.loadbalancer.server.port=${API_PORT}'
      - 'traefik.http.routers.growth-api.entrypoints=web,websecure'
      - 'traefik.http.routers.growth-api.service=growth-api'
      - 'traefik.http.routers.growth-api.tls=true'
      - 'traefik.http.routers.growth-api.tls.certresolver=${CERT_RESOLVER}'
    networks:
      - default
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ['CMD', 'wget', 'http://localhost:${API_PORT}']
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 10s

  proxy:
    container_name: "growthbook-proxy"
    image: growthbook/proxy:git-efec2de
    env_file: ./proxy/.env
    networks:
      - default
    labels:
      - 'traefik.enable=${TRAEFIK_ENABLE}'
      - 'traefik.http.routers.growth-proxy.rule=Host(`${HOST}`)'
      - 'traefik.http.services.growth-proxy.loadbalancer.server.port=${PORT}'
      - 'traefik.http.routers.growth-proxy.entrypoints=web,websecure'
      - 'traefik.http.routers.growth-proxy.service=growth-proxy'
      - 'traefik.http.routers.growth-proxy.tls=true'
      - 'traefik.http.routers.growth-proxy.tls.certresolver=${CERT_RESOLVER}'
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    #healthcheck:
    #  test: ['CMD', 'curl', '-f', 'http://localhost:${PORT}/healthcheck']
    #  interval: 20s
    #  timeout: 5s
    #  retries: 3
    #  start_period: 10s
    depends_on:
      - growthbook

networks:
  default:
    name: traefik
    external: true
