volumes:
  prometheus-data:
    name: prometheus-data
    driver: local
    labels:
      - "co.anitrend.id=prometheus-data"
  loki-data:
    name: loki-data
    driver: local
    labels:
      - "co.anitrend.id=loki-data"
  tempo-data:
    name: tempo-data
    driver: local
    labels:
      - "co.anitrend.id=tempo-data"
  grafana-data:
    name: grafana-data
    driver: local
    labels:
      - "co.anitrend.id=grafana-data"

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.120.0
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
    networks:
      default:
        aliases:
          - otel-collector
    command: ["--config=/etc/otel-collector/config.yaml"]
    volumes:
      - ./observability/otel/config.yaml:/etc/otel-collector/config.yaml
    ports:
      - "${OTLP_GRPC_PORT}:4317"   # OTLP gRPC
      - "${METRICS_PORT}:8888"      # Internal metrics
      - "${PROM_METRICS_PORT}:8889" # Prometheus exporter metrics
      - "${HEALTH_CHECK_PORT}:13133" # Health check extension
    env_file: ./observability/otel/.env
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE}"
      - "traefik.http.routers.otel.rule=Host(`${HOST}`)"
      - "traefik.http.routers.otel.entrypoints=web,websecure"
      - "traefik.http.routers.otel.service=otel"
      - "traefik.http.routers.otel.middlewares=sso@docker"
      - "traefik.http.routers.otel.tls=true"
      - "traefik.http.routers.otel.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.services.otel.loadbalancer.server.port=${PORT}"
    depends_on:
      - loki
      - tempo
      - prometheus
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  prometheus:
    image: prom/prometheus:v2.55.1
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
    networks:
      default:
        aliases:
          - prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.size=${STORAGE_TSDB_RETENTION_SIZE}'
      - '--web.enable-remote-write-receiver'
    volumes:
      - ./observability/prometheus/config/:/etc/prometheus/
      - prometheus-data:/prometheus
    env_file: ./observability/prometheus/.env
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE}"
      - "traefik.http.routers.prometheus.rule=Host(`${HOST}`)"
      - "traefik.http.routers.prometheus.entrypoints=web,websecure"
      - "traefik.http.routers.prometheus.service=prometheus"
      - "traefik.http.routers.prometheus.middlewares=sso@docker"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.services.prometheus.loadbalancer.server.port=${PORT}"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  loki:
    image: grafana/loki:3.4.2
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
    networks:
      default:
        aliases:
          - loki
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./observability/loki/config.yaml:/etc/loki/config.yaml
      - loki-data:/loki
    env_file: ./observability/loki/.env
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  tempo:
    image: grafana/tempo:2.7.1
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
    networks:
      default:
        aliases:
          - tempo
    command: ["-config.file=/etc/tempo/config.yaml"]
    volumes:
      - ./observability/tempo/tempo.yaml:/etc/tempo/config.yaml
      - tempo-data:/tmp/tempo
    env_file: ./observability/tempo/.env
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    image: grafana/grafana-oss:11.5.2
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
    networks:
      default:
        aliases:
          - grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ./observability/grafana/config/provisioning/:/etc/grafana/provisioning/
    env_file: ./observability/grafana/.env
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE}"
      - "traefik.http.routers.grafana.rule=Host(`${HOST}`)"
      - "traefik.http.routers.grafana.entrypoints=web,websecure"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.services.grafana.loadbalancer.server.port=${PORT}"
    depends_on:
      - prometheus
      - loki
      - tempo
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: traefik-public
    external: true 