---
x-stack: platform
services:
  doco-cd:
    image: ghcr.io/kimdre/doco-cd:0.106.0
    container_name: doco-cd
    networks:
      - default
    env_file: .env
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE}"
      - "traefik.http.routers.doco.rule=Host(`${HOST}`)"
      - "traefik.http.routers.doco.entrypoints=web,websecure"
      - "traefik.http.routers.doco.service=doco"
      - "traefik.http.routers.doco.tls=true"
      - "traefik.http.routers.doco.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.services.doco.loadbalancer.server.port=${PORT}"
      - "traefik.http.services.doco.loadbalancer.healthcheck.path=/health"
    restart: unless-stopped
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: 3
    environment:
      POLL_CONFIG: |
        - url: https://github.com/AniTrend/local-stack.git
          reference: refs/heads/dev
          interval: 300s
    volumes:
      - doco-cd-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - doco_webhook_secret
      - doco_api_secret

secrets:
  doco_webhook_secret:
    file: ./secrets/webhook_secret
  doco_api_secret:
    file: ./secrets/api_secret

volumes:
  doco-cd-data:

networks:
  default:
    name: traefik
    external: true
