<<<<<<< Updated upstream
---
x-stack: observability
=======
>>>>>>> Stashed changes
volumes:
  loki-data:
    name: loki-data
    driver: local
<<<<<<< Updated upstream
    # external: true
services:
  loki:
    container_name: loki
    image: grafana/loki:3.7.3
=======

services:
  loki:
    container_name: loki
    image: grafana/loki:3.4.2
>>>>>>> Stashed changes
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./config.yaml:/etc/loki/config.yaml
      - loki-data:/loki
    env_file: .env
    networks:
      - default
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
<<<<<<< Updated upstream
        max-file: 3
=======
        max-file: "3"
>>>>>>> Stashed changes

networks:
  default:
    name: traefik
    external: true
