version: '3'

volumes:
  traefik-ssl-certs:
    driver: local

services:
  traefik:
    container_name: "traefik"
    image: traefik:v3.2
    networks:
      - default
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./auth/htpasswd:/etc/htpasswd:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - /etc/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE}"
      - "traefik.http.routers.traefik-ui.rule=Host(`${HOST}`)"
      - "traefik.http.routers.traefik-ui.entrypoints=web,websecure"
      - "traefik.http.routers.traefik-ui.service=api@internal"
      - "traefik.http.routers.traefik-ui.middlewares=sso"
      - "traefik.http.routers.traefik-ui.tls=true"
      - "traefik.http.routers.traefik-ui.tls.certresolver=${CERT_RESOLVER}"
      #- "traefik.http.routers.traefik-ui.tls.domains[0].main=${HOST}"
      #- "traefik.http.routers.traefik-ui.tls.domains[0].sans=${HOST_SANS}"
      - "traefik.http.middlewares.sso.plugin.trauth.domain=${TRUEAUTH_DOMAIN}"
      - "traefik.http.middlewares.sso.plugin.trauth.cookiename=${TRUEAUTH_COOKIE}"
      - "traefik.http.middlewares.sso.plugin.trauth.users=${SSO_CREDENTIALS}"
      - "traefik.http.services.traefik-ui.loadbalancer.server.port=${PORT}"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: traefik
    external: true