volumes:
  prometheus-data:
    name: prometheus-data
    driver: local
    external: true
  loki-data:
    name: loki-data
    driver: local
    external: true
  tempo-data:
    name: tempo-data
    driver: local
    external: true
  grafana-data:
    name: grafana-data
    driver: local
    external: true

services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.131.0
    command: ["--config=/etc/otel-collector/config.yaml"]
    volumes:
      - ./otel/config.yaml:/etc/otel-collector/config.yaml
    env_file: ./otel/.env
    ports:
      - "${OTLP_GRPC_PORT}:4317"   # OTLP gRPC
      - "${METRICS_PORT}:8888"      # Internal metrics
      - "${PROM_METRICS_PORT}:8889" # Prometheus exporter metrics
      - "${HEALTH_CHECK_PORT}:13133" # Health check extension
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE}"
      - "traefik.http.routers.otel.rule=Host(`${HOST}`)"
      - "traefik.http.routers.otel.entrypoints=web,websecure"
      - "traefik.http.routers.otel.service=otel"
      - "traefik.http.routers.otel.middlewares=sso@docker"
      - "traefik.http.routers.otel.tls=true"
      - "traefik.http.routers.otel.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.services.otel.loadbalancer.server.port=${PORT}"
    depends_on:
      - loki
      - tempo
      - prometheus
    networks:
      - default
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.5.0
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.size=${STORAGE_TSDB_RETENTION_SIZE}'
      - '--web.enable-remote-write-receiver'
    volumes:
      - ./prometheus/config/:/etc/prometheus/
      - prometheus-data:/prometheus
    env_file: ./prometheus/.env
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE}"
      - "traefik.http.routers.prometheus.rule=Host(`${HOST}`)"
      - "traefik.http.routers.prometheus.entrypoints=web,websecure"
      - "traefik.http.routers.prometheus.service=prometheus"
      - "traefik.http.routers.prometheus.middlewares=sso@docker"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.services.prometheus.loadbalancer.server.port=${PORT}"
    networks:
      - default
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  loki:
    container_name: loki
    image: grafana/loki:3.5.3
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./loki/config.yaml:/etc/loki/config.yaml
      - loki-data:/loki
    env_file: ./loki/.env
    networks:
      - default
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  tempo:
    container_name: tempo
    image: grafana/tempo:2.8.1
    command: ["-config.file=/etc/tempo/config.yaml"]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo/config.yaml
      - tempo-data:/tmp/tempo
    env_file: ./tempo/.env
    networks:
      - default
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:12.1.0
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/config/provisioning/:/etc/grafana/provisioning/
    env_file: ./grafana/.env
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE}"
      - "traefik.http.routers.grafana.rule=Host(`${HOST}`)"
      - "traefik.http.routers.grafana.entrypoints=web,websecure"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.services.grafana.loadbalancer.server.port=${PORT}"
    depends_on:
      - prometheus
      - loki
      - tempo
    networks:
      - default
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: traefik
    external: true 