# http:
#   routers:
#     traefik-ui:
#       entryPoints:
#         - web
#         - websecure
#       rule: "Host(`traefik.docker.localhost`)"
#       service: "api@internal"
#       middlewares:
#         - "sso"
# 
#   middlewares:
#     sso:
#       plugin:
#         trauth:
#           domain: "docker.localhost"
#           cookiename: "sso-cookie"
#           users: "${SSO_CREDENTIALS}"
# 
#   services:
#     traefik-ui:
#       loadBalancer:
#         server:
#           port: 8080
# 
#   tls:
#     domains:
#       - main: "docker.localhost"
#         sans:
#           - "*.docker.localhost"
# 
# tls:
#   certificates:
#     - certFile: "/certs/local-cert.pem"
#       keyFile: "/certs/local-key.pem"