---
volumes:
  grafana-data:
    name: 'grafana-data'
    driver: local

services:
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:12.3.2
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/provisioning/:/etc/grafana/provisioning/
    env_file: .env
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE}"
      - "traefik.http.routers.grafana.rule=Host(`${HOST}`)"
      - "traefik.http.routers.grafana.entrypoints=web,websecure"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.services.grafana.loadbalancer.server.port=${PORT}"
    networks:
      - default
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: traefik
    external: true
