volumes:
  cache:
    name: apisix-cache
    labels:
      - "co.anitrend.id=apisix-cache"
    driver: local
  etcd-data:
    name: 'etcd-data'
    labels:
      - "co.anitrend.id=etcd-data"
    driver: local

services:
  apisix_dashboard:
    container_name: "apisix-dashobard"
    image: apache/apisix-dashboard:3.0.1-alpine
    networks:
      - default
    env_file:
      - ./api-dashboard/.env
    volumes:
      - ./api-dashboard/config/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE}"
      - "traefik.http.routers.apisix-dashboard.rule=Host(`${HOST}`)"
      - "traefik.http.routers.apisix-dashboard.entrypoints=web,websecure"
      - "traefik.http.routers.apisix-dashboard.service=apisix-dashboard"
      - "traefik.http.routers.apisix-dashboard.tls=true"
      - "traefik.http.routers.apisix-dashboard.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.services.apisix-dashboard.loadbalancer.server.port=${PORT}"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - apisix_gateway

  apisix_gateway:
    container_name: "apisix-gateway"
    image: apache/apisix:3.13.0-debian
    networks:
      - default
    env_file:
      - ./api-gateway/.env
    volumes:
      - ./api-gateway/config/apisix.yaml:/usr/local/apisix/conf/config.yaml:ro
      - cache:/tmp/apisix-cache/
    restart: unless-stopped
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE}"
      - "traefik.http.routers.apisix.rule=Host(`${HOST}`)"
      - "traefik.http.routers.apisix.entrypoints=web,websecure"
      - "traefik.http.routers.apisix.service=apisix"
      - "traefik.http.routers.apisix.tls=true"
      - "traefik.http.routers.apisix.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.services.apisix.loadbalancer.server.port=${PORT}"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - etcd

  etcd:
    container_name: "apisix-etcd"
    image: bitnami/etcd:3.6.3
    networks:
      - default
    env_file: 
      - ./etcd/.env
    volumes:
      - etcd-data:/bitnami/etcd
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: traefik
    external: true
