---
volumes:
  otel-data:
    name: otel-data
    driver: local

services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.147.0
    command: ["--config=/etc/otel-collector/config.yaml"]
    volumes:
      - ./config.yaml:/etc/otel-collector/config.yaml
    env_file: .env
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE}"
      - "traefik.tcp.routers.otel.rule=HostSNI(`${HOST}`)"
      - "traefik.tcp.routers.otel.entrypoints=web,websecure"
      - "traefik.tcp.routers.otel.service=otel"
      - "traefik.tcp.routers.otel.tls=true"
      - "traefik.tcp.routers.otel.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.tcp.services.otel.loadbalancer.server.port=${PORT}"
    networks:
      - default
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: traefik
    external: true
