<<<<<<< Updated upstream
---
x-stack: observability
volumes:
  otel-data:
    name: otel-data
    driver: local

services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.155.0
    command: ["--config=/etc/otel-collector/config.yaml"]
    volumes:
      - ./config.yaml:/etc/otel-collector/config.yaml
    env_file: .env
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE}"
      - "traefik.tcp.routers.otel.rule=HostSNI(`${HOST}`)"
      - "traefik.tcp.routers.otel.entrypoints=web,websecure"
      - "traefik.tcp.routers.otel.service=otel"
      - "traefik.tcp.routers.otel.tls=true"
      - "traefik.tcp.routers.otel.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.tcp.services.otel.loadbalancer.server.port=${PORT}"
=======
services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.120.0
    command: ["--config=/etc/otel-collector/config.yaml"]
    volumes:
      - ./config.yaml:/etc/otel-collector/config.yaml
    ports:
      - "${OTLP_GRPC_PORT}:4317"
      - "${METRICS_PORT}:8888"
      - "${PROM_METRICS_PORT}:8889"
      - "${HEALTH_CHECK_PORT}:13133"
    env_file: .env
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE}"
      - "traefik.http.routers.otel.rule=Host(`${HOST}`)"
      - "traefik.http.routers.otel.entrypoints=web,websecure"
      - "traefik.http.routers.otel.service=otel"
      - "traefik.http.routers.otel.middlewares=sso@docker"
      - "traefik.http.routers.otel.tls=true"
      - "traefik.http.routers.otel.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.services.otel.loadbalancer.server.port=${PORT}"
>>>>>>> Stashed changes
    networks:
      - default
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
<<<<<<< Updated upstream
        max-file: 3
=======
        max-file: "3"
>>>>>>> Stashed changes

networks:
  default:
    name: traefik
    external: true
