version: '3'

services:
    postgres:
      container_name: "postgres"
      image: postgres:16
      networks:
        - default
      ports:
        - ${PORT}:${PORT}
      env_file: .env
      labels:
        - "traefik.enable=true"
        - "traefik.tcp.routers.postgres.rule=HostSNI(`${HOST}`)"
        - "traefik.tcp.routers.postgres.entrypoints=websecure"
        - "traefik.tcp.routers.postgres.service=postgres"
        - "traefik.tcp.routers.postgres.tls=true"
        - "traefik.tcp.routers.postgres.tls.certresolver=staging"
        - "traefik.tcp.services.postgres.loadbalancer.server.port=${PORT}"
      logging:
        options:
          max-size: "10m"
          max-file: "3"

networks:
  default:
    name: traefik
    external: true