version: '3'

services:
  mongo:
    container_name: "mongo"
    image: mongo:7.0.8
    networks:
      - default
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    volumes:
      - ./data/db:/data/db
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mongo.rule=HostSNI(`${HOST}`)"
      - "traefik.tcp.routers.mongo.entrypoints=websecure"
      - "traefik.tcp.routers.mongo.service=mongo"
      - "traefik.tcp.routers.mongo.tls=true"
      - "traefik.tcp.routers.mongo.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.tcp.services.mongo.loadbalancer.server.port=${PORT}"

networks:
  default:
    name: traefik
    external: true