version: '3'

services:
  redis:
    container_name: "redis"
    image: redis:7.4-alpine
    networks:
      - default
    command: redis-server --appendonly yes
    env_file: .env
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE}"
      - "traefik.tcp.routers.redis.rule=HostSNI(`${HOST}`)"
      - "traefik.tcp.routers.redis.entrypoints=web,websecure"
      - "traefik.tcp.routers.redis.service=redis"
      - "traefik.tcp.routers.redis.tls=true"
      - "traefik.tcp.routers.redis.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.tcp.services.redis.loadbalancer.server.port=${PORT}"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: traefik
    external: true
